language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm # on Trusty only
  - nightly
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  # make sure git tests do not complain about user/email not being set
  - git config --global user.name nicdev
  - git config --global user.email nic@epiclabs.com
script:
  - vendor/bin/phpunit
